<a href="https://colab.research.google.com/github/Chandrapraksh-prajapat/Regex/blob/main/Advance_Python/Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 11-june-2026

In [ ]:
# What is Feature Engineering ?

# => In Feature engineering we basically create more features or reduce features on the basis of our requirement

In [ ]:
#  Why do we need feature engineering ?

# Data ==> preprocessing ==> Eda ==> Model evaluation  ==> Model training ==> Model selection ==> feature enginnering  & selection

#  => Feature engineering is the process of transforming raw data into meaningful inputs for machine learning algorithms.
#     It is the foundation of a successful AI project:
#     it unlocks model accuracy, prevents overfitting, and ensures algorithms learn from the right signals

In [ ]:
# Features
# ==> Numerical => Discrete( no. of cards ) , continous (Age , weight, height)
# ==> Categorical => ordinal( Rank in class) , nominal( city , colors)

In [ ]:
# Encoding ==> the process of converting the categorical data into numeical data

# 1.one hot encoding ( small data )
# 2.get_dummies( one hot encoding by pandas )
# 3.ordinal encoding
# 4.label encoding

In [ ]:
#  One Hot Encoding =>  One-hot encoding is a preprocessing technique used to convert categorical data into a numerical format
                      #  so that machine learning algorithms can understand and process it.


# One-hot encoding works by representing each category as a binary vector (a sequence of 0s and 1s)
#  where only one position is "hot" (1) and all others are 0.

In [ ]:
import pandas as pd

data ={
    'Name' : ['Ram','Shyam','Kalu'],
    'City' : ['Noida', 'Jaipur', 'Delhi']
}

df=pd.DataFrame(data)
df

    Name    City
0    Ram   Noida
1  Shyam  Jaipur
2   Kalu   Delhi

In [ ]:
# First method using pandas

# df = pd.get_dummies(df, columns=['City'],dtype=int)
# df

In [ ]:
# Second method using sklearn (Imp for ML pipeline)

from sklearn.preprocessing import OneHotEncoder
en=OneHotEncoder(sparse_output=False)  #create variable
encode_data= en.fit_transform(df[['City']])

data=pd.DataFrame(encode_data,columns=en.get_feature_names_out())
data

   City_Delhi  City_Jaipur  City_Noida
0         0.0          0.0         1.0
1         0.0          1.0         0.0
2         1.0          0.0         0.0

# 12-06-2026

In [ ]:
#  Label Encoder

from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

data ={
    'pass/fail' : ['pass','fail','pass','fail']
}

df=pd.DataFrame(data)
df

  pass/fail
0      pass
1      fail
2      pass
3      fail

In [ ]:
le=LabelEncoder()
df['pass/fail']=le.fit_transform(df['pass/fail'])
df

   pass/fail
0          1
1          0
2          1
3          0

In [ ]:

data ={
    'pass/fail' : ['pass','fail','pass','fail'],
    'customer_feedback' : ['good','better','best','better']
}
df=pd.DataFrame(data)
df

  pass/fail customer_feedback
0      pass              good
1      fail            better
2      pass              best
3      fail            better

In [ ]:
oe=OrdinalEncoder(categories=[['good','better','best']])

In [ ]:
df['Encoded_data']=oe.fit_transform(df[['customer_feedback']])
df

  pass/fail customer_feedback  Encoded_data
0      pass              good           0.0
1      fail            better           1.0
2      pass              best           2.0
3      fail            better           1.0

In [ ]:
# tain test split
# implementation
# dependent and independent variable
# feature scaling
# normalization
# revision

# 15-06-2026

In [18]:
# Feature scaling
# standardization (Z-Score)
# Normalization (Min max scaling )

import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
data = {
    'Area': [200, 300, 400, 500, 600],
    'Population' : [30000, 50000,70000, 90000, 95000]
}

df=pd.DataFrame(data)
df

   Area  Population
0   200       30000
1   300       50000
2   400       70000
3   500       90000
4   600       95000

In [13]:
scaler=MinMaxScaler()
df['Scaled_Area']=scaler.fit_transform(df[['Area']])
df

   Area  Population  Scaled_Area
0   200       30000         0.00
1   300       50000         0.25
2   400       70000         0.50
3   500       90000         0.75
4   600       95000         1.00

In [14]:
scaler=StandardScaler()
df['Scaled_Area']=scaler.fit_transform(df[['Area']])
df

   Area  Population  Scaled_Area
0   200       30000    -1.414214
1   300       50000    -0.707107
2   400       70000     0.000000
3   500       90000     0.707107
4   600       95000     1.414214

In [19]:
#  apply on multiple column
scaler=StandardScaler()
scaled_data=scaler.fit_transform(df[['Area','Population']])
pd.DataFrame(scaled_data,columns=df.columns)

       Area  Population
0 -1.414214   -1.515579
1 -0.707107   -0.696347
2  0.000000    0.122885
3  0.707107    0.942117
4  1.414214    1.146925

In [ ]:
#  How to handle outliers in data

# we generally drop the outliers when we have small number of outliers
# but without discussing with the team we cant drop that entry

# We cap the outliers with boundary value( upper , lower )



# Steps:-
# visualize the data
# verify outlier are genuine or erros
# remove only obvious erros
#  for valid outliers - capping , transformations ,
#                      robust scaling or models

In [26]:
# handle outliers with IQR method

import pandas as pd
df=pd.DataFrame({
    'salary':[500, 20000,25000,27000,30000,31000,500000] }
 )

Q1=df['salary'].quantile(0.25)
Q3=df['salary'].quantile(0.75)
IQR=Q3-Q1

lower=Q1-1.5*IQR
upper=Q3+1.5*IQR

# df[(df['salary']<lower) | (df['salary']>upper)]

# lower bound se chhoti values lower bound se replace ho jayegi
# upper bound se badi values upper bound se replace ho jayegi
# baaki values same rhegi

df['Remove Outliers']=df['salary'].clip(lower,upper)
df

   salary  Remove Outliers
0     500            10500
1   20000            20000
2   25000            25000
3   27000            27000
4   30000            30000
5   31000            31000
6  500000            42500

In [ ]:
# percentile capping
# train test split ,
# intro to ML  & supervised - unsupervised ML